config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'
  
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]      # /category/2
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel    # /orders/8/cancel
      post :pay         # /orders/8/pay
      get :pay_confirm  # /orders/8/pay_confirm
    end

    collection do
      get :confirm    # /orders/confirm
    end
  end

  namespace :admin do
    root 'products#index' # /admin
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # PUT /admin/categories/sort
      end
    end
  end

  # POST /api/v1/subscribe
  # POST /api/v2/subscribe

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: "utils#subscribe"
      post 'cart', to: 'utils#cart'
    end
  end
end

app/views/shared/frontend/_carousel.html.erb
<div id="carousel" class="carousel">
  <div class="item-1">
    <%= image_pack_tag 'switch/switch1.jpg' %>
  </div>
  <div class="item-2">
    <%= image_pack_tag 'switch/switch2.jpg' %>
  </div>
  <div class="item-3">
    <%= image_pack_tag 'switch/switch3.jpg' %>
  </div>
  <div class="item-4">
    <%= image_pack_tag 'switch/switch4.jpg' %>
  </div>
  <div class="item-5">
    <%= image_pack_tag 'switch/switch5.jpg' %>
  </div>
  <div class="item-6">
    <%= image_pack_tag 'switch/switch6.jpg' %>
  </div>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="footer has-background-dark">
  <section class="container">
    <div class="columns">
      <div class="column">
        <div class="menu">
          <p class="menu-label">關於我們</p>
          <ul class="menu-list">
            <li><a></a></li>
            <li><a>隱私權保護政策</a></li>
            <li><a>服務條款</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">聯絡我們</p>
          <ul class="menu-list">
            <li><a>02.2393.2610</a></li>
            <li><a>業務合作談判</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">自助查詢</p>
          <ul class="menu-list">
            <li><a>銀行優惠說明</a></li>
            <li><a>LINE Points 回饋說明</a></li>
            <li><a>預購商品查詢</a></li>
            <li><a>訂單出貨查詢</a></li>
            <li><a>配送進度查詢</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">顧客服務</p>
          <ul class="menu-list">
            <li><a>VIEWS生活誌</a></li>
            <li><a>會員回饋計畫</a></li>
            <li><a>退換貨說明</a></li>
            <li><a>客服中心</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar has-shadow has-background-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_pack_tag 'logo.png' %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item field has-addons">
        <div class="control">
          <input class="input" type="text" placeholder="輸入關鍵字">
        </div>
        <div class="control">
          <a class="button is-primary">
            <i class="fas fa-search"></i>&nbsp; 搜尋
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <div class="navbar-item" data-controller="cart">
              <%= link_to cart_path do  %>
                <i class="fas fa-shopping-cart"></i>
                <span data-cart-target="count" data-action="addToCart@document->cart#updateCart">
                  (<%= current_cart.items.count %>)
                </span>
              <% end %>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <i class="fas fa-user"></i>&nbsp;<%= current_user.email %>
              </a>
              <div class="navbar-dropdown">
                <%= link_to "個人資料", edit_user_registration_path, class: 'navbar-item' %>
                <%= link_to "訂單記錄", orders_path, class: 'navbar-item' %>
                <hr class="navbar-divider">
                <%= link_to "登出", destroy_user_session_path, method: :delete, class: 'navbar-item' %>
              </div>
            </div>
          <% else %>
            <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "登入", new_user_session_path, class: 'button is-light' %>
          <% end %>          
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/frontend/_product_list.html.erb
<section class="product_list section has-background-black">

  <section class="container">

    
      <div class="columns is-multiline">
        <% products.each do |product| %>
          <div class="column is-4">
            <div class="card product-item is-shadowless">
              <div class="card-image">
                <figure class="image">
                  <%= link_to product do %>
                    <%= image_tag product.cover_image.variant(resize: '430x290') if product.cover_image.attached? %>
                  <% end %>
                </figure>
              </div>
              <div class="card-content">
                <div class="content">
                  <h4 class="is-size-6"><%= product.vendor.title %></h4>
                  <p><%= link_to product.name, product, class: 'has-text-dark' %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>


    </div>
  </section>
</section>

app/views/shared/frontend/_subscribe.html.erb
<section class="subscribe section has-background-light is-centered has-text-centered" data-controller="subscribe">
  <h3 class="has-text-centered is-size-4">訂閱電子報</h3>

  <div class="container">
    <form action="#">
      <div class="field has-addons">
        <div class="control has-icons-left is-expanded">
          <input type="email" data-subscribe-target="email" placeholder="請輸入您的 Email 信箱" name="email" class="input is-rounded">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
        <div class="control">
          <input type="submit" data-action="subscribe#add" value="訂閱電子報" class="button is-primary is-rounded">
        </div>
      </div>
    </form>
  </div>
</section>

app/views/shared/frontend/_top_menu.html.erb
<div class="tabs is-centered">
  <ul>
    <% categories.each do |category| %>
      <li><%= link_to category.name, category %></li>
    <% end %>
  </ul>
</div>