config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'
  
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]      # /category/2
  resource :cart, only: [:show, :destroy] do
    collection do
      get :checkout
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete :cancel    # /orders/8/cancel
      post :pay         # /orders/8/pay
      get :pay_confirm  # /orders/8/pay_confirm
    end

    collection do
      get :confirm    # /orders/confirm
    end
  end

  namespace :admin do
    root 'products#index' # /admin
    resources :products, except: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put :sort # PUT /admin/categories/sort
      end
    end
  end

  # POST /api/v1/subscribe
  # POST /api/v2/subscribe

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: "utils#subscribe"
      post 'cart', to: 'utils#cart'
    end
  end
end

app/models/cart.rb
# PORO = Plain Old Ruby Object
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def self.from_hash(hash = nil)
    # {
    #   "items" => [
    #     {"sku_id" => 1, "quantity" => 3},
    #     {"sku_id" => 2, "quantity" => 2}
    #   ]
    # }

    if hash && hash["items"]
      items = hash["items"].map { |item|
        CartItem.new(item["sku_id"], item["quantity"])
      }
      Cart.new(items)
    else
      Cart.new
    end
  end

  def serialize
    # items = [
    #   {"sku_id" => 1, "quantity" => 3},
    #   {"sku_id" => 2, "quantity" => 2}
    # ]

    items = @items.map { |item| {"sku_id" => item.sku_id,
                                 "quantity" => item.quantity} }

    { "items" => items }
  end

  def add_sku(sku_id)
    found = @items.find { |item| item.sku_id == sku_id }

    if found
      found.increment!
    else
      @items << CartItem.new(sku_id)
    end
    # 找...
  end

  def empty?
    @items.empty?     # 陣列內建 empty? 方法
  end

  def total_price
    # total = 0

    # @items.each do |item|
    #   total += item.total_price
    # end

    # total

    # 上面的寫法不夠 Ruby
    @items.reduce(0) { |sum, item| sum + item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
  
  def destroy
    session[:cart_9527] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    # @order = Order.new 下面是以 user 角度建立的寫法
    @order = current_user.orders.build
  end
end

app/views/carts/_cart.html.erb
<% if current_cart.empty? %>
<h1 class="title">目前購物車是空的！！！</h1>
<%= link_to '繼續選購', root_path, class: 'button is-medium' %>
<% else %>
<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>品項</th>
      <th>單價</th>
      <th>數量</th>
      <th>小計</th>
    </tr>
  </thead>
  <tbody>
    <% current_cart.items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= item.product.sell_price %></td>
        <td><%= item.quantity %></td>
        <td><%= item.total_price %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3">總價</td>
      <td><%= current_cart.total_price %></td>
    </tr>
  </tfoot>
</table>
<%= link_to '繼續選購', root_path, class: 'button is-medium' %>
<%= link_to '結帳', checkout_cart_path, class: 'button is-danger is-medium' %>
<% end %>

app/views/carts/checkout.html.erb
<section class="section">
  <h1 class="title">結帳</h1>
  <%= render 'cart' %>

  <hr>
  <h2 class="title is-5">收件人資訊</h2>

  <%= form_with(model: @order) do |form| %>
    <div class="columns">
      <div class="column">
        <div class="field">
          <%= form.label :recipient, '收件人', class: 'label' %>
          <%= form.text_field :recipient, class: 'input is-medium' %>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :tel, '電話', class: 'label' %>
          <%= form.text_field :tel, class: 'input is-medium' %>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :address, '地址', class: 'label' %>
          <%= form.text_field :address, class: 'input is-medium' %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= form.label :note, '備註說明', class: 'label' %>
      <%= form.text_area :note, class: 'textarea is-medium' %>
    </div>
    <div class="field">
      <%= form.submit '使用 Line Pay 結帳', class: 'button is-primary is-medium', data: {confirm: '確認送出'} %>
    </div>
  <% end %>
</section>

app/views/carts/show.html.erb
<section class="section">
  <h1 class="title">購物車
    <%= link_to cart_path, class: 'is-size-5', method: 'delete', data: {confirm: '確認清空購物車'} do %>
      <i class="far fa-trash-alt"></i>
      <span>清空購物車</span> 
    <% end %>
  </h1>
  <%= render 'cart' %>
</section>